### ISSUE TITLE
Why the `Data` in the periphery do not need adapter?

### ISSUE THREAD

**Issue by vicbell** [mahanhz/clean-architecture-example#2]
The `Web` has a adapter to convert data format, but the `Data` do not. Why?

**Comment by mahanhz** [comment]
I wanted to keep the adapter module free from any framework.

Since Spring Data is being used in the data module, then the adapter would need to include spring data dependencies to be able to call its JPA repositories. This would make the adapter Spring framework aware, which I wanted to avoid, so I let the data module become directly dependent on the core.

Since this is an example project, it also shows the difference between a peripheral  module depending directly on core and one that is cut off from it via an adapter.

This is just the approach I have taken here, one can certainly do it differently.
For example:
* Have the data module dependent on both core and adapter, where the conversion from entity to domain is done via an adapter
* Moving the adapter module into the periphery and making it framework aware
* Getting rid of the adapter module and having an adapter package within data and web.

**Comment by vicbell** [comment]
Thanks!
